spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
